### PR TITLE
Do not import trombi in setup.py

### PR DESCRIPTION
**Pull request by truemped**
This causes problems when using buildout, e.g. since there is no
globally installed Tornado version available. Then the "from trombi
import version" statement causes the buildout to fail!

### CODE REVIEW

**Comment by nailor** [comment]
Hmm, this really is an issue. However, the solution is bit problematic: I'd like to keep a version that could be accessed from python (for example: from trombi import version), but due to the convenience imports in `__init__.py` this probably is impossible.

Thus I'm thinking of reverting back to describing version information in `setup.py` and abandoning the version in `__init__.py` as I'm not too confident adding magical file reading in `setup.py` which probably would break in future.

**Comment by truemped** [comment]
Yes, that is a better solution. Should I do this in this pull request, or will you do this and we simply close this!?

**Comment by nailor** [comment]
If it's not too much trouble, just change it in this and I'll merge as soon as possible. Thanks for your pull request beforehand :)

**Comment by truemped** [comment]
Not at all! :)

Daniel

**Comment by nailor** [comment]
I made a minor changes to pull request: squashed the two commits together and reworded commit message a bit

**Comment by truemped** [comment]
Perfect :) Thank you!

**Pull request closed without merging**
